name: Build site on schedule or main branch update

on:
  push:
    branches:
      - main
  schedule:
    # 金曜日の 12:00 (JST) に処理を実行する。
    # UTC だと木曜日の 03:00。
    - cron: "30 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    # to https://github.com/Kkrmr/feedbacks/actions/runs/7821947452/job/21339972849
    # from https://zenn.dev/osawa_koki/articles/a63b96a2707a8f
    permissions:
      actions: write
      checks: write
      contents: write

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: "16"
      # - name: Install dependencies
      #   run: npm i
      # - name: Build the feed
      #   run: npm run build
      # From https://github.com/osmoscraft/osmosfeed-demo
      - name: Install osmosfeed
        run: npm i @osmoscraft/osmosfeed@^1.0.0
      - name: Build the feed
        run: npx osmosfeed
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
